# Generated by Django 2.1.4 on 2019-01-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_html', '0003_auto_20190103_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile_conclusion',
            name='MCV_cnt',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='patient_profile_conclusion',
            name='RBC_cnt',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='patient_profile_conclusion',
            name='patient_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient_profile_conclusion',
            name='pcv_cnt',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient_profile_conclusion',
            name='hemoglobin_cnt',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
